name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker BuildKit
        run: |
          echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
        if: runner.os == 'Linux'

      - name: Build Docker image
        run: docker build -t cypress-example .

      - name: Run Cypress tests in Docker
        run: |
          mkdir -p cypress/results
          docker run --rm \
            -v ${{ github.workspace }}/cypress/results:/e2e/cypress/results \
            cypress-example

      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: cypress/results/*.xml

      # Upload Allure results for HTML generation
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: cypress/results/allure-results/ 