name: Cypress E2E with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install dependencies
      - name: Install NPM dependencies
        run: npm ci

      # 4. Prepare Allure results folder
      - name: Prepare Allure results directory
        run: mkdir -p cypress/results/allure-results

      # 5. Run Cypress tests with Allure enabled
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          allure: true
          allureResultsPath: cypress/results/allure-results
        with:
          command: npm run cy:run

      # 6. Load previous Allure history for report continuity
      - name: Load previous Allure history
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        run: |
          npx allure generate cypress/results/allure-results --clean -o allure-report
          # Copy previous history into the new report
          mkdir -p allure-report/history
          cp -r gh-pages/history/* allure-report/history/ || true

      # 7. Publish to GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
