name: Cypress E2E with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Install dependencies
      - name: Install NPM dependencies
        run: npm ci

      # 4. Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start       # if you need a web server
          wait-on: 'http://localhost:3000'
          command: npm run cy:run

      # 5. Generate Allure HTML report (includes history)
      - name: Load previous Allure history
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        run: npx allure generate cypress/results/allure-results --clean -o allure-report

      # 6. Publish to GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
